[package]
name = "adventofcode2024"
version = "0.1.0"
authors = ["Giovanni Guarino <gioguarino@gmail.com>"]
edition = "2021"

[lib]
bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"